### ISSUE TITLE
PlatformIO 3.0 Roadmap

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#423]
# Milestone [3.0](https://github.com/platformio/platformio/milestones/3.0.0)
- [x] Measure code coverage by tests and report results to online service #101 
- [x] Handle specific extra build flags from library.json #289 
- [ ] Add openOCD support #341
- [ ] Allow GDB protocol for ARM-based platforms #342
- [x] Proper way to import mbed library #361 
- [ ] Automatically update IDE settings according to project data #364 
- [x] Unit testing for embedded #408 
- [x] Support versioning librarys via semver #410
- [x] Depend on a specific version of a library #413
- [x] Make it possible to install libraries by name #414
- [x] Check library compatibility with project environment before building #415
- [ ] Show detailed info about library using "platformio lib show" command #430
- [x] Automatically build and include dependent libraries #432
- [ ] init --ide eclipse deletes linkedResources #443
- [x] Board compatibility with more than one platform #456 
- [x] Replace TYPE for board/platform with ID #459 
- [x] Allow library.json to specify sources other than PlatformIO's Repository #461 
- [ ] Discover OTA-able esp8266/Arduino modules using dns-sd #463
- [x] Local and global libraries #475 
- [x] "platform.json" manifest for development platform #479
- [x] Depend on a library using GitHub URL #498
- [x] Add nrf51822 ble library #507 
- [ ] How can I list available libraries without being horribly, horribly annoying.  #511 
- [ ] Add support for board definition inside project directory #515
- [x] Add Support for local ("PC") unit tests #519 
- [x] license field in library.json #522 
- [x] Implement "lib_extra_dirs" option for project environment #537 
- [x]  Build System: Attach custom Before/Pre and After/Post actions for targets #542 
- [x] Replace "lib_use" with "lib_force" #556 
- [ ] Use hooks from CVS to update library #557 
- [x] BuildDependentLibraries ignores src_filter #570 
- [x] Apply strict search for lib dependencies #588 
- [x] Implement detailed debug information for library dependencies #617 
- [x] Dynamic variables/templates for use in platformio.ini #705
- [x] BBC MicroBit configuration #709 
- [x] Allow to disable library archiving #719
- [x] Print human-readable information when processing environments #721 

# Install the latest PlatformIO 3.0 development version

See http://docs.platformio.org/en/latest/installation.html#development-version

# Documentation

http://docs.platformio.org/en/latest/

**Comment by Obijuan** [comment]
I've already written the code for an initial support for the Lattice ice40 FPGA new platform (issue #480) I would like to pull-request it (for Platformio 3.0)

My questions are:
1)  Can I proceed? or should I wait for something
2) In case I can proceed. Should I create a branch of develop? or of feature/platformio-30? or of another?

Thanks a lot for your work

**Comment by Obijuan** [comment]
Just waiting for an answer on how to proceed. If no answer i will create a branch from develop an emitt the pull request

**Comment by ivankravets** [comment]
@Obijuan PlatformIO 3.0 will not contain `builder/scripts` folder with platform. All platforms will live in separate repositories. 

Please wait for PlatformIO 3.0. I will report here further steps.

Thanks.

**Comment by Obijuan** [comment]
ok. Thanks
